"use client";
import React, { useState, useEffect } from "react";
import { AlertTriangle, Bookmark, Edit, Key, Search } from "lucide-react";
import Recipie from "@/components/Recipie";
import getRecipie from "@/libs/getRecipie";
import RecipieDetails from "@/components/RecipieDetails";
import Image from "next/image";
// import imageEl from "/../public/images/forky..png";
// import icon from "../public/images/forky..png";
const recipies = [
  {
    idMeal: "52807",
    strMeal: "Baingan Bharta",
    strDrinkAlternate: null,
    strCategory: "Vegetarian",
    strArea: "Indian",
    strInstructions:
      "Rinse the baingan (eggplant or aubergine) in water. Pat dry with a kitchen napkin. Apply some oil all over and\r\nkeep it for roasting on an open flame. You can also grill the baingan or roast in the oven. But then you won't get\r\nthe smoky flavor of the baingan. Keep the eggplant turning after a 2 to 3 minutes on the flame, so that its evenly\r\ncooked. You could also embed some garlic cloves in the baingan and then roast it.\r\n2. Roast the aubergine till its completely cooked and tender. With a knife check the doneness. The knife should slid\r\neasily in aubergines without any resistance. Remove the baingan and immerse in a bowl of water till it cools\r\ndown.\r\n3. You can also do the dhungar technique of infusing charcoal smoky flavor in the baingan. This is an optional step.\r\nUse natural charcoal for this method. Heat a small piece of charcoal on flame till it becomes smoking hot and red.\r\n4. Make small cuts on the baingan with a knife. Place the red hot charcoal in the same plate where the roasted\r\naubergine is kept. Add a few drops of oil on the charcoal. The charcoal would begin to smoke.\r\n5. As soon as smoke begins to release from the charcoal, cover the entire plate tightly with a large bowl. Allow the\r\ncharcoal smoke to get infused for 1 to 2 minutes. The more you do, the more smoky the baingan bharta will\r\nbecome. I just keep for a minute. Alternatively, you can also do this dhungar method once the baingan bharta is\r\ncooked, just like the way we do for Dal Tadka.\r\n6. Peel the skin from the roasted and smoked eggplant.\r\n7. Chop the cooked eggplant finely or you can even mash it.\r\n8. In a kadai or pan, heat oil. Then add finely chopped onions and garlic.\r\n9. Saute the onions till translucent. Don't brown them.\r\n10. Add chopped green chilies and saute for a minute.\r\n11. Add the chopped tomatoes and mix it well.\r\n12. Bhuno (saute) the tomatoes till the oil starts separating from the mixture.\r\n13. Now add the red chili powder. Stir and mix well.\r\n14. Add the chopped cooked baingan.\r\n15. Stir and mix the chopped baingan very well with the onion­tomato masala mixture.\r\n16. Season with salt. Stir and saute for some more 4 to 5 minutes more.\r\n17. Finally stir in the coriander leaves with the baingan bharta or garnish it with them. Serve Baingan Bharta with\r\nphulkas, rotis or chapatis. It goes well even with bread, toasted or grilled bread and plain rice or jeera rice.",
    strMealThumb:
      "https://www.themealdb.com/images/media/meals/urtpqw1487341253.jpg",
    strTags: "Spicy,Bun,Calorific",
    strYoutube: "https://www.youtube.com/watch?v=-84Zz2EP4h4",
    strIngredient1: "Aubergine",
    strIngredient2: "Onion",
    strIngredient3: "Tomatoes",
    strIngredient4: "Garlic",
    strIngredient5: "Green Chili",
    strIngredient6: "Red Chili Powder",
    strIngredient7: "Oil",
    strIngredient8: "Coriander Leaves",
    strIngredient9: "salt",
    strIngredient10: "",
    strIngredient11: "",
    strIngredient12: "",
    strIngredient13: "",
    strIngredient14: "",
    strIngredient15: "",
    strIngredient16: "",
    strIngredient17: "",
    strIngredient18: "",
    strIngredient19: "",
    strIngredient20: "",
    strMeasure1: "1 large",
    strMeasure2: "½ cup ",
    strMeasure3: "1 cup",
    strMeasure4: "6 cloves",
    strMeasure5: "1",
    strMeasure6: "¼ teaspoon",
    strMeasure7: "1.5 tablespoon",
    strMeasure8: "1 tablespoon chopped",
    strMeasure9: "as required",
    strMeasure10: "",
    strMeasure11: "",
    strMeasure12: "",
    strMeasure13: "",
    strMeasure14: "",
    strMeasure15: "",
    strMeasure16: "",
    strMeasure17: "",
    strMeasure18: "",
    strMeasure19: "",
    strMeasure20: "",
    strSource:
      "http://www.vegrecipesofindia.com/baingan-bharta-recipe-punjabi-baingan-bharta-recipe/",
    strImageSource: null,
    strCreativeCommonsConfirmed: null,
    dateModified: null,
  },
  {
    idMeal: "52987",
    strMeal: "Lasagna Sandwiches",
    strDrinkAlternate: null,
    strCategory: "Pasta",
    strArea: "American",
    strInstructions:
      "1. In a small bowl, combine the first four ingredients; spread on four slices of bread. Layer with bacon, tomato and cheese; top with remaining bread.\r\n\r\n2. In a large skillet or griddle, melt 2 tablespoons butter. Toast sandwiches until lightly browned on both sides and cheese is melted, adding butter if necessary.\r\n\r\nNutrition Facts\r\n1 sandwich: 445 calories, 24g fat (12g saturated fat), 66mg cholesterol, 1094mg sodium, 35g carbohydrate (3g sugars, 2g fiber), 21g protein.",
    strMealThumb:
      "https://www.themealdb.com/images/media/meals/xr0n4r1576788363.jpg",
    strTags: "Sandwich",
    strYoutube: "",
    strIngredient1: "Sour Cream",
    strIngredient2: "Chopped Onion",
    strIngredient3: "Dried Oregano",
    strIngredient4: "Salt",
    strIngredient5: "Bread",
    strIngredient6: "Bacon",
    strIngredient7: "Tomato",
    strIngredient8: "Mozzarella",
    strIngredient9: "Butter",
    strIngredient10: "",
    strIngredient11: "",
    strIngredient12: "",
    strIngredient13: "",
    strIngredient14: "",
    strIngredient15: "",
    strIngredient16: "",
    strIngredient17: "",
    strIngredient18: "",
    strIngredient19: "",
    strIngredient20: "",
    strMeasure1: "1/4 cup",
    strMeasure2: "2 tbs",
    strMeasure3: "1/2 tbs",
    strMeasure4: "1/4 tsp",
    strMeasure5: "8 slices",
    strMeasure6: "8 slices",
    strMeasure7: "8 slices",
    strMeasure8: "4 slices",
    strMeasure9: "2 1/2 Tbs",
    strMeasure10: " ",
    strMeasure11: " ",
    strMeasure12: " ",
    strMeasure13: " ",
    strMeasure14: " ",
    strMeasure15: " ",
    strMeasure16: " ",
    strMeasure17: " ",
    strMeasure18: " ",
    strMeasure19: " ",
    strMeasure20: " ",
    strSource: "",
    strImageSource: null,
    strCreativeCommonsConfirmed: null,
    dateModified: null,
  },

  {
    idMeal: "52844",
    strMeal: "Lasagne",
    strDrinkAlternate: null,
    strCategory: "Pasta",
    strArea: "Italian",
    strInstructions:
      "Heat the oil in a large saucepan. Use kitchen scissors to snip the bacon into small pieces, or use a sharp knife to chop it on a chopping board. Add the bacon to the pan and cook for just a few mins until starting to turn golden. Add the onion, celery and carrot, and cook over a medium heat for 5 mins, stirring occasionally, until softened.\r\nAdd the garlic and cook for 1 min, then tip in the mince and cook, stirring and breaking it up with a wooden spoon, for about 6 mins until browned all over.\r\nStir in the tomato purée and cook for 1 min, mixing in well with the beef and vegetables. Tip in the chopped tomatoes. Fill each can half full with water to rinse out any tomatoes left in the can, and add to the pan. Add the honey and season to taste. Simmer for 20 mins.\r\nHeat oven to 200C/180C fan/gas 6. To assemble the lasagne, ladle a little of the ragu sauce into the bottom of the roasting tin or casserole dish, spreading the sauce all over the base. Place 2 sheets of lasagne on top of the sauce overlapping to make it fit, then repeat with more sauce and another layer of pasta. Repeat with a further 2 layers of sauce and pasta, finishing with a layer of pasta.\r\nPut the crème fraîche in a bowl and mix with 2 tbsp water to loosen it and make a smooth pourable sauce. Pour this over the top of the pasta, then top with the mozzarella. Sprinkle Parmesan over the top and bake for 25–30 mins until golden and bubbling. Serve scattered with basil, if you like.",
    strMealThumb:
      "https://www.themealdb.com/images/media/meals/wtsvxx1511296896.jpg",
    strTags: null,
    strYoutube: "https://www.youtube.com/watch?v=gfhfsBPt46s",
    strIngredient1: "Olive Oil",
    strIngredient2: "Bacon",
    strIngredient3: "Onion",
    strIngredient4: "Celery",
    strIngredient5: "Carrots",
    strIngredient6: "Garlic",
    strIngredient7: "Minced Beef",
    strIngredient8: "Tomato Puree",
    strIngredient9: "Chopped Tomatoes",
    strIngredient10: "Honey",
    strIngredient11: "Lasagne Sheets",
    strIngredient12: "Creme Fraiche",
    strIngredient13: "Mozzarella Balls",
    strIngredient14: "Parmesan Cheese",
    strIngredient15: "Basil Leaves",
    strIngredient16: "",
    strIngredient17: "",
    strIngredient18: "",
    strIngredient19: "",
    strIngredient20: "",
    strMeasure1: "1 tblsp ",
    strMeasure2: "2",
    strMeasure3: "1 finely chopped ",
    strMeasure4: "1 Stick",
    strMeasure5: "1 medium",
    strMeasure6: "2 cloves chopped",
    strMeasure7: "500g",
    strMeasure8: "1 tbls",
    strMeasure9: "800g",
    strMeasure10: "1 tblsp ",
    strMeasure11: "500g",
    strMeasure12: "400ml",
    strMeasure13: "125g",
    strMeasure14: "50g",
    strMeasure15: "Topping",
    strMeasure16: "",
    strMeasure17: "",
    strMeasure18: "",
    strMeasure19: "",
    strMeasure20: "",
    strSource: "https://www.bbcgoodfood.com/recipes/classic-lasagne",
    strImageSource: null,
    strCreativeCommonsConfirmed: null,
    dateModified: null,
  },
  {
    idMeal: "53059",
    strMeal: "Mushroom soup with buckwheat",
    strDrinkAlternate: null,
    strCategory: "Side",
    strArea: "Croatian",
    strInstructions:
      "Chop the onion and garlic, slice the mushrooms and wash the buckwheat. Heat the oil and lightly sauté the onion. Add the mushrooms and the garlic and continue to sauté. Add the salt, vegetable seasoning, buckwheat and the bay leaf and cover with water. Simmer gently and just before it is completely cooked, add pepper, sour cream mixed with flour, the chopped parsley and vinegar to taste.",
    strMealThumb:
      "https://www.themealdb.com/images/media/meals/1ngcbf1628770793.jpg",
    strTags: "Warming, Soup",
    strYoutube: "https://www.youtube.com/watch?v=M1ok7mG9-Qc",
    strIngredient1: "Mushrooms",
    strIngredient2: "Buckwheat",
    strIngredient3: "Vegetable Oil",
    strIngredient4: "Onion",
    strIngredient5: "Garlic",
    strIngredient6: "Bay Leaf",
    strIngredient7: "Vegetable Stock Cube",
    strIngredient8: "Sour Cream",
    strIngredient9: "White Wine Vinegar",
    strIngredient10: "Parsley",
    strIngredient11: "",
    strIngredient12: "",
    strIngredient13: "",
    strIngredient14: "",
    strIngredient15: "",
    strIngredient16: "",
    strIngredient17: "",
    strIngredient18: "",
    strIngredient19: "",
    strIngredient20: "",
    strMeasure1: "150g",
    strMeasure2: "50g",
    strMeasure3: "4 tbs",
    strMeasure4: "40g",
    strMeasure5: "2 cloves",
    strMeasure6: "1",
    strMeasure7: "1tbsp",
    strMeasure8: "50 ml ",
    strMeasure9: "Dash",
    strMeasure10: "Top",
    strMeasure11: " ",
    strMeasure12: " ",
    strMeasure13: " ",
    strMeasure14: " ",
    strMeasure15: " ",
    strMeasure16: " ",
    strMeasure17: " ",
    strMeasure18: " ",
    strMeasure19: " ",
    strMeasure20: " ",
    strSource:
      "https://www.visit-croatia.co.uk/croatian-cuisine/croatian-recipes/",
    strImageSource: null,
    strCreativeCommonsConfirmed: null,
    dateModified: null,
  },
  {
    idMeal: "52948",
    strMeal: "Wontons",
    strDrinkAlternate: null,
    strCategory: "Pork",
    strArea: "Chinese",
    strInstructions:
      "Combine pork, garlic, ginger, soy sauce, sesame oil, and vegetables in a bowl.\r\nSeparate wonton skins.\r\nPlace a heaping teaspoon of filling in the center of the wonton.\r\nBrush water on 2 borders of the skin, covering 1/4 inch from the edge.\r\nFold skin over to form a triangle, sealing edges.\r\nPinch the two long outside points together.\r\nHeat oil to 450 degrees and fry 4 to 5 at a time until golden.\r\nDrain and serve with sauce.",
    strMealThumb: "https://www.themealdb.com/images/media/meals/1525876468.jpg",
    strTags: "MainMeal",
    strYoutube: "https://www.youtube.com/watch?v=9h9No18ZyCI",
    strIngredient1: "Pork",
    strIngredient2: "Garlic Clove",
    strIngredient3: "Ginger",
    strIngredient4: "Soy Sauce",
    strIngredient5: "Sesame Seed Oil",
    strIngredient6: "Carrots",
    strIngredient7: "Celery",
    strIngredient8: "Spring Onions",
    strIngredient9: "Wonton Skin",
    strIngredient10: "Oil",
    strIngredient11: "Water",
    strIngredient12: "",
    strIngredient13: "",
    strIngredient14: "",
    strIngredient15: "",
    strIngredient16: "",
    strIngredient17: "",
    strIngredient18: "",
    strIngredient19: "",
    strIngredient20: "",
    strMeasure1: "1lb",
    strMeasure2: "3 chopped",
    strMeasure3: "1 tsp ",
    strMeasure4: "1 tbs",
    strMeasure5: "1 tsp ",
    strMeasure6: "3 finely chopped",
    strMeasure7: "3 finely chopped",
    strMeasure8: "6 chopped",
    strMeasure9: "1 Packet",
    strMeasure10: "Fry",
    strMeasure11: "Bottle",
    strMeasure12: "",
    strMeasure13: "",
    strMeasure14: "",
    strMeasure15: "",
    strMeasure16: "",
    strMeasure17: "",
    strMeasure18: "",
    strMeasure19: "",
    strMeasure20: "",
    strSource: "http://www.geniuskitchen.com/recipe/chinese-wontons-20235",
    strImageSource: null,
    strCreativeCommonsConfirmed: null,
    dateModified: null,
  },
  {
    idMeal: "52808",
    strMeal: "Lamb Rogan josh",
    strDrinkAlternate: null,
    strCategory: "Lamb",
    strArea: "Indian",
    strInstructions:
      "\r\nPut the onions in a food processor and whizz until very finely chopped. Heat the oil in a large heavy-based pan, then fry the onion with the lid on, stirring every now and then, until it is really golden and soft. Add the garlic and ginger, then fry for 5 mins more.\r\nTip the curry paste, all the spices and the bay leaves into the pan, with the tomato purée. Stir well over the heat for about 30 secs, then add the meat and 300ml water. Stir to mix, turn down the heat, then add the yogurt.\r\nCover the pan, then gently simmer for 40-60 mins until the meat is tender and the sauce nice and thick. Serve scattered with coriander, with plain basmati or pilau rice.",
    strMealThumb:
      "https://www.themealdb.com/images/media/meals/vvstvq1487342592.jpg",
    strTags: "Curry,Spicy,Alcoholic",
    strYoutube: "https://www.youtube.com/watch?v=NZVo32n7iS8",
    strIngredient1: "Onion",
    strIngredient2: "Sunflower Oil",
    strIngredient3: "Garlic",
    strIngredient4: "Ginger",
    strIngredient5: "Madras Paste",
    strIngredient6: "Paprika",
    strIngredient7: "cinnamon stick",
    strIngredient8: "Cardamom",
    strIngredient9: "Clove",
    strIngredient10: "Bay Leaf",
    strIngredient11: "Tomato Purée",
    strIngredient12: "Lamb",
    strIngredient13: "Greek yogurt",
    strIngredient14: "Coriander",
    strIngredient15: "",
    strIngredient16: "",
    strIngredient17: "",
    strIngredient18: "",
    strIngredient19: "",
    strIngredient20: "",
    strMeasure1: "2 quartered",
    strMeasure2: "4 tbsp",
    strMeasure3: "4 cloves",
    strMeasure4: "Thumb sized peeled and very finely grated",
    strMeasure5: "2 tbsp",
    strMeasure6: "2 tsp",
    strMeasure7: "1",
    strMeasure8: "6 bashed to break shells",
    strMeasure9: "4",
    strMeasure10: "2",
    strMeasure11: "1 tbsp",
    strMeasure12: "1kg cubed",
    strMeasure13: "150ml",
    strMeasure14: "Garnish chopped ",
    strMeasure15: "",
    strMeasure16: "",
    strMeasure17: "",
    strMeasure18: "",
    strMeasure19: "",
    strMeasure20: "",
    strSource: "http://www.bbcgoodfood.com/recipes/9643/onepan-rogan-josh",
    strImageSource: null,
    strCreativeCommonsConfirmed: null,
    dateModified: null,
  },
  {
    idMeal: "53016",
    strMeal: "Chick-Fil-A Sandwich",
    strDrinkAlternate: null,
    strCategory: "Chicken",
    strArea: "American",
    strInstructions:
      "Wrap the chicken loosely between plastic wrap and pound gently with the flat side of a meat tenderizer until about 1/2 inch thick all around.\r\nCut into two pieces, as even as possible.\r\nMarinate in the pickle juice for 30 minutes to one hour (add a teaspoon of Tabasco sauce now for a spicy sandwich).\r\nBeat the egg with the milk in a bowl.\r\nCombine the flour, sugar, and spices in another bowl.\r\nDip the chicken pieces each into the egg on both sides, then coat in flour on both sides.\r\nHeat the oil in a skillet (1/2 inch deep) to about 345-350.\r\nFry each cutlet for 2 minutes on each side, or until golden and cooked through.\r\nBlot on paper and serve on toasted buns with pickle slices.",
    strMealThumb:
      "https://www.themealdb.com/images/media/meals/sbx7n71587673021.jpg",
    strTags: null,
    strYoutube: "https://www.youtube.com/watch?v=1WDesu7bUDM",
    strIngredient1: "Chicken Breast",
    strIngredient2: "Pickle Juice",
    strIngredient3: "Egg",
    strIngredient4: "Milk",
    strIngredient5: "Flour",
    strIngredient6: "Icing Sugar",
    strIngredient7: "Paprika",
    strIngredient8: "Salt",
    strIngredient9: "Black Pepper",
    strIngredient10: "Garlic Powder",
    strIngredient11: "Celery Salt",
    strIngredient12: "Cayenne Pepper",
    strIngredient13: "Olive Oil",
    strIngredient14: "Sesame Seed Burger Buns",
    strIngredient15: "",
    strIngredient16: "",
    strIngredient17: "",
    strIngredient18: "",
    strIngredient19: "",
    strIngredient20: "",
    strMeasure1: "1",
    strMeasure2: "1/4 cup",
    strMeasure3: "1",
    strMeasure4: "1/4 cup",
    strMeasure5: "1/2 cup ",
    strMeasure6: "1 tbs",
    strMeasure7: "1/2 tsp",
    strMeasure8: "1/2 tsp",
    strMeasure9: "1/4 tsp",
    strMeasure10: "1/4 tsp",
    strMeasure11: "1/4 tsp",
    strMeasure12: "1/2 tsp",
    strMeasure13: "1 cup ",
    strMeasure14: "1",
    strMeasure15: " ",
    strMeasure16: " ",
    strMeasure17: " ",
    strMeasure18: " ",
    strMeasure19: " ",
    strMeasure20: " ",
    strSource: "https://hilahcooking.com/chick-fil-a-copycat/",
    strImageSource: null,
    strCreativeCommonsConfirmed: null,
    dateModified: null,
  },
  {
    idMeal: "52773",
    strMeal: "Honey Teriyaki Salmon",
    strDrinkAlternate: null,
    strCategory: "Seafood",
    strArea: "Japanese",
    strInstructions:
      "Mix all the ingredients in the Honey Teriyaki Glaze together. Whisk to blend well. Combine the salmon and the Glaze together.\r\n\r\nHeat up a skillet on medium-low heat. Add the oil, Pan-fry the salmon on both sides until it’s completely cooked inside and the glaze thickens.\r\n\r\nGarnish with sesame and serve immediately.",
    strMealThumb:
      "https://www.themealdb.com/images/media/meals/xxyupu1468262513.jpg",
    strTags: "Fish,Breakfast,DateNight",
    strYoutube: "https://www.youtube.com/watch?v=4MpYuaJsvRw",
    strIngredient1: "Salmon",
    strIngredient2: "Olive oil",
    strIngredient3: "Soy Sauce",
    strIngredient4: "Sake",
    strIngredient5: "Sesame Seed",
    strIngredient6: "",
    strIngredient7: "",
    strIngredient8: "",
    strIngredient9: "",
    strIngredient10: "",
    strIngredient11: "",
    strIngredient12: "",
    strIngredient13: "",
    strIngredient14: "",
    strIngredient15: "",
    strIngredient16: null,
    strIngredient17: null,
    strIngredient18: null,
    strIngredient19: null,
    strIngredient20: null,
    strMeasure1: "1 lb",
    strMeasure2: "1 tablespoon",
    strMeasure3: "2 tablespoons",
    strMeasure4: "2 tablespoons",
    strMeasure5: "4 tablespoons",
    strMeasure6: "",
    strMeasure7: "",
    strMeasure8: "",
    strMeasure9: "",
    strMeasure10: "",
    strMeasure11: "",
    strMeasure12: "",
    strMeasure13: "",
    strMeasure14: "",
    strMeasure15: "",
    strMeasure16: null,
    strMeasure17: null,
    strMeasure18: null,
    strMeasure19: null,
    strMeasure20: null,
    strSource: null,
    strImageSource: null,
    strCreativeCommonsConfirmed: null,
    dateModified: null,
  },
  {
    idMeal: "52891",
    strMeal: "Blackberry Fool",
    strDrinkAlternate: null,
    strCategory: "Dessert",
    strArea: "British",
    strInstructions:
      "For the biscuits, preheat the oven to 200C/180C (fan)/Gas 6 and line two large baking trays with baking parchment. Scatter the nuts over a baking tray and roast in the oven for 6-8 minutes, or until golden-brown. Watch them carefully so that they don’t have a chance to burn. Remove from the oven, tip onto a board and leave to cool.\r\nPut the butter and sugar in a large bowl and beat with a wooden spoon until light and creamy. Roughly chop the cooled nuts and add to the creamed butter and sugar, along with the lemon zest, flour and baking powder. Stir well until the mixture comes together and forms a ball – you may need to use your hands.\r\nDivide the biscuit dough into 24 even pieces and roll into small balls. Place the balls the prepared baking trays, spaced well apart to allow for spreading.\r\nPress the biscuits to flatten to around 1cm/½in thick. Bake the biscuits, one tray at a time, for 12 minutes or until very pale golden-brown. Leave to cool on the trays. They will be very soft when you take them out of the oven, but will crisp as they cool.\r\nStore in an airtight tin and eat within five days.\r\nFor the fool, rinse the blackberries in a colander to wash away any dust or dirt. Put the blackberries in a non-stick saucepan and sprinkle over the caster sugar.\r\nStir in the lemon juice and heat gently for two minutes, or until the blackberries begin to soften and release their juices. Remove and reserve 12 blackberries for decoration and continue cooking the rest.\r\nSimmer the blackberries very gently for 15 minutes, stirring regularly until very soft and squidgy. Remove from the heat and press the berries and juice through a sieve over a bowl, using the bottom of a ladle to help you extract as much of the purée as possible. Leave the purée to cool and discard the seeds. You should end up with around 325ml/11fl oz of purée.\r\nPut the cream and yoghurt in a large bowl and whip with an electric whisk until soft peaks form when the whisk is removed from the bowl – the acidity of the fruit will thicken the cream further, so don’t take it too far.\r\nWhen the purée is completely cold, adjust the sweetness to taste by adding more sugar if needed. Pour it into the bowl with the whipped cream and yoghurt and stir just once or twice until very lightly combined.\r\nSpoon the blackberry fool into individual wide, glass dishes – or one large, single bowl. It should look quite marbled, so don’t over-stir it. Scatter a few tiny mint leaves on top and decorate with the reserved blackberries. Sprinkle with a little sugar if you like and serve with the hazelnut biscuits.",
    strMealThumb:
      "https://www.themealdb.com/images/media/meals/rpvptu1511641092.jpg",
    strTags: "Desert,Summer,Fruity,Dairy",
    strYoutube: "https://www.youtube.com/watch?v=kniRGjDLFrQ",
    strIngredient1: "Hazlenuts",
    strIngredient2: "Butter",
    strIngredient3: "Caster Sugar",
    strIngredient4: "Lemon",
    strIngredient5: "Plain Flour",
    strIngredient6: "Baking Powder",
    strIngredient7: "Blackberrys",
    strIngredient8: "Sugar",
    strIngredient9: "Caster Sugar",
    strIngredient10: "Lemon Juice",
    strIngredient11: "Double Cream",
    strIngredient12: "Yogurt",
    strIngredient13: "Mint",
    strIngredient14: "",
    strIngredient15: "",
    strIngredient16: "",
    strIngredient17: "",
    strIngredient18: "",
    strIngredient19: "",
    strIngredient20: "",
    strMeasure1: "50g",
    strMeasure2: "125g",
    strMeasure3: "150g",
    strMeasure4: "Grated",
    strMeasure5: "150g",
    strMeasure6: "½ tsp",
    strMeasure7: "600g",
    strMeasure8: "75g",
    strMeasure9: "2 tbs",
    strMeasure10: "1 tbs",
    strMeasure11: "300ml ",
    strMeasure12: "100ml",
    strMeasure13: "Garnish with",
    strMeasure14: "",
    strMeasure15: "",
    strMeasure16: "",
    strMeasure17: "",
    strMeasure18: "",
    strMeasure19: "",
    strMeasure20: "",
    strSource: "https://www.bbc.co.uk/food/recipes/blackberry_fool_with_11859",
    strImageSource: null,
    strCreativeCommonsConfirmed: null,
    dateModified: null,
  },
  {
    idMeal: "52791",
    strMeal: "Eton Mess",
    strDrinkAlternate: null,
    strCategory: "Dessert",
    strArea: "British",
    strInstructions:
      "Purée half the strawberries in a blender. Chop the remaining strawberries, reserving four for decoration.\r\nWhip the double cream until stiff peaks form, then fold in the strawberry purée and crushed meringue. Fold in the chopped strawberries and ginger cordial, if using.\r\nSpoon equal amounts of the mixture into four cold wine glasses. Serve garnished with the remaining strawberries and a sprig of mint.",
    strMealThumb:
      "https://www.themealdb.com/images/media/meals/uuxwvq1483907861.jpg",
    strTags: "Dairy,Fruity,Desert,Treat,Speciality",
    strYoutube: "https://www.youtube.com/watch?v=43WgiNq54L8",
    strIngredient1: "strawberries",
    strIngredient2: "double cream",
    strIngredient3: "meringue nests",
    strIngredient4: "ginger cordial",
    strIngredient5: "Mint",
    strIngredient6: "",
    strIngredient7: "",
    strIngredient8: "",
    strIngredient9: "",
    strIngredient10: "",
    strIngredient11: "",
    strIngredient12: "",
    strIngredient13: "",
    strIngredient14: "",
    strIngredient15: "",
    strIngredient16: "",
    strIngredient17: "",
    strIngredient18: "",
    strIngredient19: "",
    strIngredient20: "",
    strMeasure1: "500g",
    strMeasure2: "400ml",
    strMeasure3: "3 x 7.5cm",
    strMeasure4: "1 tbsp",
    strMeasure5: "sprigs of fresh",
    strMeasure6: "",
    strMeasure7: "",
    strMeasure8: "",
    strMeasure9: "",
    strMeasure10: "",
    strMeasure11: "",
    strMeasure12: "",
    strMeasure13: "",
    strMeasure14: "",
    strMeasure15: "",
    strMeasure16: "",
    strMeasure17: "",
    strMeasure18: "",
    strMeasure19: "",
    strMeasure20: "",
    strSource: "",
    strImageSource: null,
    strCreativeCommonsConfirmed: null,
    dateModified: null,
  },
  {
    idMeal: "52954",
    strMeal: "Hot and Sour Soup",
    strDrinkAlternate: null,
    strCategory: "Pork",
    strArea: "Chinese",
    strInstructions:
      "STEP 1 - MAKING THE SOUP\r\nIn a wok add chicken broth and wait for it to boil.\r\nNext add salt, sugar, sesame seed oil, white pepper, hot pepper sauce, vinegar and soy sauce and stir for few seconds.\r\nAdd Tofu, mushrooms, black wood ear mushrooms to the wok.\r\nTo thicken the sauce, whisk together 1 Tablespoon of cornstarch and 2 Tablespoon of water in a bowl and slowly add to your soup until it's the right thickness.\r\nNext add 1 egg slightly beaten with a knife or fork and add it to the soup and stir for 8 seconds\r\nServe the soup in a bowl and add the bbq pork and sliced green onions on top.",
    strMealThumb: "https://www.themealdb.com/images/media/meals/1529445893.jpg",
    strTags: "Soup",
    strYoutube: "https://www.youtube.com/watch?v=KgV9Zq3aSTo",
    strIngredient1: "Mushrooms",
    strIngredient2: "Wood Ear Mushrooms",
    strIngredient3: "Tofu",
    strIngredient4: "Pork",
    strIngredient5: "Chicken Stock",
    strIngredient6: "Salt",
    strIngredient7: "Sugar",
    strIngredient8: "Sesame Seed Oil",
    strIngredient9: "Pepper",
    strIngredient10: "Hotsauce",
    strIngredient11: "Vinegar",
    strIngredient12: "Soy Sauce",
    strIngredient13: "Cornstarch",
    strIngredient14: "Water",
    strIngredient15: "Spring Onions",
    strIngredient16: "",
    strIngredient17: "",
    strIngredient18: "",
    strIngredient19: "",
    strIngredient20: "",
    strMeasure1: "1/3 cup",
    strMeasure2: "1/3 cup",
    strMeasure3: "2/3 Cup",
    strMeasure4: "1/2 cup ",
    strMeasure5: "2-1/2 cups",
    strMeasure6: "1/2 tsp",
    strMeasure7: "1/4 tsp",
    strMeasure8: "1 tsp ",
    strMeasure9: "1/4 tsp",
    strMeasure10: "1/2 tsp",
    strMeasure11: "1-½ cups",
    strMeasure12: "1 tsp ",
    strMeasure13: "1 tbs",
    strMeasure14: "2 tbs",
    strMeasure15: "1/4 cup",
    strMeasure16: "",
    strMeasure17: "",
    strMeasure18: "",
    strMeasure19: "",
    strMeasure20: "",
    strSource: "https://sueandgambo.com/pages/chinese-hot-and-sour-soup",
    strImageSource: null,
    strCreativeCommonsConfirmed: null,
    dateModified: null,
  },
  {
    idMeal: "52972",
    strMeal: "Tunisian Lamb Soup",
    strDrinkAlternate: null,
    strCategory: "Lamb",
    strArea: "Tunisian",
    strInstructions:
      "Add the lamb to a casserole and cook over high heat. When browned, remove from the heat and set aside.\r\nKeep a tablespoon of fat in the casserole and discard the rest. Reduce to medium heat then add the garlic, onion and spinach and cook until the onion is translucent and the spinach wilted or about 5 minutes.\r\nReturn the lamb to the casserole with the onion-spinach mixture, add the tomato puree, cumin, harissa, chicken, chickpeas, lemon juice, salt and pepper in the pan. Simmer over low heat for about 20 minutes.\r\nAdd the pasta and cook for 15 minutes or until pasta is cooked.",
    strMealThumb:
      "https://www.themealdb.com/images/media/meals/t8mn9g1560460231.jpg",
    strTags: "Soup",
    strYoutube: "https://www.youtube.com/watch?v=w1qgTQmLRe4",
    strIngredient1: "Lamb Mince",
    strIngredient2: "Garlic",
    strIngredient3: "Onion",
    strIngredient4: "Spinach",
    strIngredient5: "Tomato Puree",
    strIngredient6: "Cumin",
    strIngredient7: "Chicken Stock",
    strIngredient8: "Harissa Spice",
    strIngredient9: "Chickpeas",
    strIngredient10: "Lemon Juice",
    strIngredient11: "Macaroni",
    strIngredient12: "Salt",
    strIngredient13: "Pepper",
    strIngredient14: "",
    strIngredient15: "",
    strIngredient16: "",
    strIngredient17: "",
    strIngredient18: "",
    strIngredient19: "",
    strIngredient20: "",
    strMeasure1: "500g",
    strMeasure2: "2 cloves minced",
    strMeasure3: "1",
    strMeasure4: "300g",
    strMeasure5: "3 tbs",
    strMeasure6: "1 tbs",
    strMeasure7: "1 Litre",
    strMeasure8: "3 tsp",
    strMeasure9: "400g",
    strMeasure10: "1/2 ",
    strMeasure11: "150g",
    strMeasure12: "Pinch",
    strMeasure13: "Pinch",
    strMeasure14: " ",
    strMeasure15: " ",
    strMeasure16: " ",
    strMeasure17: " ",
    strMeasure18: " ",
    strMeasure19: " ",
    strMeasure20: " ",
    strSource: "http://allrecipes.co.uk/recipe/16694/tunisian-lamb-soup.aspx",
    strImageSource: null,
    strCreativeCommonsConfirmed: null,
    dateModified: null,
  },
  {
    idMeal: "52893",
    strMeal: "Apple & Blackberry Crumble",
    strDrinkAlternate: null,
    strCategory: "Dessert",
    strArea: "British",
    strInstructions:
      "Heat oven to 190C/170C fan/gas 5. Tip the flour and sugar into a large bowl. Add the butter, then rub into the flour using your fingertips to make a light breadcrumb texture. Do not overwork it or the crumble will become heavy. Sprinkle the mixture evenly over a baking sheet and bake for 15 mins or until lightly coloured.\r\nMeanwhile, for the compote, peel, core and cut the apples into 2cm dice. Put the butter and sugar in a medium saucepan and melt together over a medium heat. Cook for 3 mins until the mixture turns to a light caramel. Stir in the apples and cook for 3 mins. Add the blackberries and cinnamon, and cook for 3 mins more. Cover, remove from the heat, then leave for 2-3 mins to continue cooking in the warmth of the pan.\r\nTo serve, spoon the warm fruit into an ovenproof gratin dish, top with the crumble mix, then reheat in the oven for 5-10 mins. Serve with vanilla ice cream.",
    strMealThumb:
      "https://www.themealdb.com/images/media/meals/xvsurr1511719182.jpg",
    strTags: "Pudding",
    strYoutube: "https://www.youtube.com/watch?v=4vhcOwVBDO4",
    strIngredient1: "Plain Flour",
    strIngredient2: "Caster Sugar",
    strIngredient3: "Butter",
    strIngredient4: "Braeburn Apples",
    strIngredient5: "Butter",
    strIngredient6: "Demerara Sugar",
    strIngredient7: "Blackberrys",
    strIngredient8: "Cinnamon",
    strIngredient9: "Ice Cream",
    strIngredient10: "",
    strIngredient11: "",
    strIngredient12: "",
    strIngredient13: "",
    strIngredient14: "",
    strIngredient15: "",
    strIngredient16: "",
    strIngredient17: "",
    strIngredient18: "",
    strIngredient19: "",
    strIngredient20: "",
    strMeasure1: "120g",
    strMeasure2: "60g",
    strMeasure3: "60g",
    strMeasure4: "300g",
    strMeasure5: "30g",
    strMeasure6: "30g",
    strMeasure7: "120g",
    strMeasure8: "¼ teaspoon",
    strMeasure9: "to serve",
    strMeasure10: "",
    strMeasure11: "",
    strMeasure12: "",
    strMeasure13: "",
    strMeasure14: "",
    strMeasure15: "",
    strMeasure16: "",
    strMeasure17: "",
    strMeasure18: "",
    strMeasure19: "",
    strMeasure20: "",
    strSource:
      "https://www.bbcgoodfood.com/recipes/778642/apple-and-blackberry-crumble",
    strImageSource: null,
    strCreativeCommonsConfirmed: null,
    dateModified: null,
  },
  {
    idMeal: "52870",
    strMeal: "Chickpea Fajitas",
    strDrinkAlternate: null,
    strCategory: "Vegetarian",
    strArea: "Mexican",
    strInstructions:
      "Heat oven to 200C/180C fan/gas 6 and line a baking tray with foil. Drain the chickpeas, pat dry and tip onto the prepared baking tray. Add the oil and paprika, toss to coat, then roast for 20-25 mins until browned and crisp, shaking halfway through cooking.\r\n\r\nMeanwhile, put the tomatoes and onion in a small bowl with the vinegar and set aside to pickle. Put the avocado in another bowl and mash with a fork, leaving some larger chunks. Stir in the lime juice and season well. Mix the soured cream with the harissa and set aside until ready to serve.\r\n\r\nHeat a griddle pan until nearly smoking. Add the tortillas , one at a time, charring each side until hot with griddle lines. \r\n\r\nPut everything on the table and build the fajitas : spread a little of the harissa cream over the tortilla, top with roasted chickpeas, guacamole, pickled salsa and coriander, if you like. Serve with the lime wedges for squeezing over.",
    strMealThumb:
      "https://www.themealdb.com/images/media/meals/tvtxpq1511464705.jpg",
    strTags: "Vegetarian",
    strYoutube: "https://www.youtube.com/watch?v=LGY3V7EGpT0",
    strIngredient1: "Chickpeas",
    strIngredient2: "Olive Oil",
    strIngredient3: "Paprika",
    strIngredient4: "Tomatoes",
    strIngredient5: "Red Onions",
    strIngredient6: "Red Wine Vinegar",
    strIngredient7: "Avocado",
    strIngredient8: "Lime",
    strIngredient9: "Lime",
    strIngredient10: "Sour Cream",
    strIngredient11: "Harissa Spice",
    strIngredient12: "Corn Tortillas",
    strIngredient13: "Coriander",
    strIngredient14: "",
    strIngredient15: "",
    strIngredient16: "",
    strIngredient17: "",
    strIngredient18: "",
    strIngredient19: "",
    strIngredient20: "",
    strMeasure1: "400g",
    strMeasure2: "1 tblsp ",
    strMeasure3: "pinch",
    strMeasure4: "2 small cut chunks",
    strMeasure5: "1 finely sliced",
    strMeasure6: "2 tsp",
    strMeasure7: "1",
    strMeasure8: "Juice of 1",
    strMeasure9: "Chopped",
    strMeasure10: "100g ",
    strMeasure11: "2 tsp",
    strMeasure12: "4",
    strMeasure13: "to serve",
    strMeasure14: "",
    strMeasure15: "",
    strMeasure16: "",
    strMeasure17: "",
    strMeasure18: "",
    strMeasure19: "",
    strMeasure20: "",
    strSource: "https://www.bbcgoodfood.com/recipes/chickpea-fajitas",
    strImageSource: null,
    strCreativeCommonsConfirmed: null,
    dateModified: null,
  },
  {
    idMeal: "53012",
    strMeal: "Gigantes Plaki",
    strDrinkAlternate: null,
    strCategory: "Vegetarian",
    strArea: "Greek",
    strInstructions:
      "Soak the beans overnight in plenty of water. Drain, rinse, then place in a pan covered with water. Bring to the boil, reduce the heat, then simmer for approx 50 mins until slightly tender but not soft. Drain, then set aside.\r\n\r\nHeat oven to 180C/160C fan/gas 4. Heat the olive oil in a large frying pan, tip in the onion and garlic, then cook over a medium heat for 10 mins until softened but not browned. Add the tomato purée, cook for a further min, add remaining ingredients, then simmer for 2-3 mins. Season generously, then stir in the beans. Tip into a large ovenproof dish, then bake for approximately 1 hr, uncovered and without stirring, until the beans are tender. The beans will absorb all the fabulous flavours and the sauce will thicken. Allow to cool, then scatter with parsley and drizzle with a little more olive oil to serve.",
    strMealThumb:
      "https://www.themealdb.com/images/media/meals/b79r6f1585566277.jpg",
    strTags: null,
    strYoutube: "https://www.youtube.com/watch?v=e-2K2iyPASA",
    strIngredient1: "Butter Beans",
    strIngredient2: "Olive Oil",
    strIngredient3: "Onion",
    strIngredient4: "Garlic Clove",
    strIngredient5: "Tomato Puree",
    strIngredient6: "Tomatoes",
    strIngredient7: "Sugar",
    strIngredient8: "Dried Oregano",
    strIngredient9: "Cinnamon",
    strIngredient10: "Chopped Parsley",
    strIngredient11: "",
    strIngredient12: "",
    strIngredient13: "",
    strIngredient14: "",
    strIngredient15: "",
    strIngredient16: "",
    strIngredient17: "",
    strIngredient18: "",
    strIngredient19: "",
    strIngredient20: "",
    strMeasure1: "400g",
    strMeasure2: "3 tbs",
    strMeasure3: "1 chopped",
    strMeasure4: "2 chopped",
    strMeasure5: "2 tbs",
    strMeasure6: "800g",
    strMeasure7: "1 tbs",
    strMeasure8: "1 tbs",
    strMeasure9: "Pinch",
    strMeasure10: "2 tbs",
    strMeasure11: " ",
    strMeasure12: " ",
    strMeasure13: " ",
    strMeasure14: " ",
    strMeasure15: " ",
    strMeasure16: " ",
    strMeasure17: " ",
    strMeasure18: " ",
    strMeasure19: " ",
    strMeasure20: " ",
    strSource: "https://www.bbcgoodfood.com/recipes/gigantes-plaki",
    strImageSource: null,
    strCreativeCommonsConfirmed: null,
    dateModified: null,
  },
  {
    idMeal: "52793",
    strMeal: "Sticky Toffee Pudding Ultimate",
    strDrinkAlternate: null,
    strCategory: "Dessert",
    strArea: "British",
    strInstructions:
      "Stone and chop the dates quite small, put them in a bowl, then pour the boiling water over. Leave for about 30 mins until cool and well-soaked, then mash a bit with a fork. Stir in the vanilla extract. Butter and flour seven mini pudding tins (each about 200ml/7fl oz) and sit them on a baking sheet. Heat oven to 180C/fan 160C/gas 4.\r\nWhile the dates are soaking, make the puddings. Mix the flour and bicarbonate of soda together and beat the eggs in a separate bowl. Beat the butter and sugar together in a large bowl for a few mins until slightly creamy (the mixture will be grainy from the sugar). Add the eggs a little at a time, beating well between additions. Beat in the black treacle then, using a large metal spoon, gently fold in one-third of the flour, then half the milk, being careful not to overbeat. Repeat until all the flour and milk is used. Stir the soaked dates into the pudding batter. The mix may look a little curdled at this point and will be like a soft, thick batter. Spoon it evenly between the tins and bake for 20-25 mins, until risen and firm.\r\nMeanwhile, put the sugar and butter for the sauce in a medium saucepan with half the cream. Bring to the boil over a medium heat, stirring all the time, until the sugar has completely dissolved. Stir in the black treacle, turn up the heat slightly and let the mixture bubble away for 2-3 mins until it is a rich toffee colour, stirring occasionally to make sure it doesn’t burn. Take the pan off the heat and beat in the rest of the cream.\r\nRemove the puddings from the oven. Leave in the tins for a few mins, then loosen them well from the sides of the tins with a small palette knife before turning them out. You can serve them now with the sauce drizzled over, but they’ll be even stickier if left for a day or two coated in the sauce. To do this, pour about half the sauce into one or two ovenproof serving dishes. Sit the upturned puddings on the sauce, then pour the rest of the sauce over them. Cover with a loose tent of foil so that the sauce doesn’t smudge (no need to chill).\r\nWhen ready to serve, heat oven to 180C/fan 160C/gas 4. Warm the puddings through, still covered, for 15-20 mins or until the sauce is bubbling. Serve them on their own, or with cream or custard.",
    strMealThumb:
      "https://www.themealdb.com/images/media/meals/xrptpq1483909204.jpg",
    strTags: "Pudding,Desert,Cake,Dairy",
    strYoutube: "https://www.youtube.com/watch?v=hKq6RbxJHBo",
    strIngredient1: "Medjool dates",
    strIngredient2: "water",
    strIngredient3: "vanilla extract",
    strIngredient4: "self-raising flour",
    strIngredient5: "bicarbonate of soda",
    strIngredient6: "eggs",
    strIngredient7: "butter",
    strIngredient8: "demerara sugar",
    strIngredient9: "black treacle",
    strIngredient10: "milk",
    strIngredient11: "ice cream",
    strIngredient12: "muscovado sugar",
    strIngredient13: "butter",
    strIngredient14: "double cream",
    strIngredient15: "black treacle",
    strIngredient16: "",
    strIngredient17: "",
    strIngredient18: "",
    strIngredient19: "",
    strIngredient20: "",
    strMeasure1: "225g",
    strMeasure2: "175ml Boiling",
    strMeasure3: "1 tsp",
    strMeasure4: "175g",
    strMeasure5: "1 tsp",
    strMeasure6: "2",
    strMeasure7: "85g",
    strMeasure8: "140g",
    strMeasure9: "2 tbsp",
    strMeasure10: "100ml",
    strMeasure11: "1 scoop",
    strMeasure12: "175g",
    strMeasure13: "50g",
    strMeasure14: "225ml",
    strMeasure15: "1 tbsp",
    strMeasure16: "",
    strMeasure17: "",
    strMeasure18: "",
    strMeasure19: "",
    strMeasure20: "",
    strSource: "https://www.youtube.com/watch?v=Wytv3bjqJII",
    strImageSource: null,
    strCreativeCommonsConfirmed: null,
    dateModified: null,
  },
  {
    idMeal: "52875",
    strMeal: "Chicken Ham and Leek Pie",
    strDrinkAlternate: null,
    strCategory: "Chicken",
    strArea: "British",
    strInstructions:
      "Heat the chicken stock in a lidded saucepan. Add the chicken breast and bring to a low simmer. Cover with a lid and cook for 10 minutes. Remove the chicken breasts from the water with tongs and place on a plate. Pour the cooking liquor into a large jug.\r\nMelt 25g/1oz of the butter in a large heavy-based saucepan over a low heat. Stir in the leeks and fry gently for two minutes, stirring occasionally until just softened. Add the garlic and cook for a further minute. Add the remaining butter and stir in the flour as soon as the butter has melted. Cook for 30 seconds, stirring constantly.\r\nSlowly pour the milk into the pan, just a little at a time, stirring well between each adding. Gradually add 250ml/10fl oz of the reserved stock and the wine, if using, stirring until the sauce is smooth and thickened slightly. Bring to a gentle simmer and cook for 3 minutes.\r\nSeason the mixture, to taste, with salt and freshly ground black pepper. Remove from the heat and stir in the cream. Pour into a large bowl and cover the surface of the sauce with cling ilm to prevent a skin forming. Set aside to cool.\r\nPreheat the oven to 200C/400F/Gas 6. Put a baking tray in the oven to heat.\r\nFor the pastry, put the flour and butter in a food processor and blend on the pulse setting until the mixture resembles fine breadcrumbs. With the motor running, add the beaten egg and water and blend until the mixture forms a ball. Portion off 250g/10oz of pastry for the lid.\r\nRoll the remaining pastry out on a lightly floured surface, turning the pastry frequently until around 5mm/¼in thick and 4cm/1½in larger than the pie dish. Lift the pastry over the rolling pin and place it gently into the pie dish. Press the pastry firmly up the sides, making sure there are no air bubbles. Leave the excess pastry overhanging the sides.\r\nCut the chicken breasts into 3cm/1¼in pieces. Stir the chicken, ham and leeks into the cooled sauce. Pour the chicken filling into the pie dish. Brush the rim of the dish with beaten egg. Roll out the reserved pastry for the lid.\r\nCover the pie with the pastry lid and press the edges together firmly to seal. Trim any excess pastry.\r\nMake a small hole in the centre of the pie with the tip of a knife. Glaze the top of the pie with beaten egg. Bake on the preheated tray in the centre of the oven for 35-40 minutes or until the pie is golden-brown all over and the filling is piping hot.",
    strMealThumb:
      "https://www.themealdb.com/images/media/meals/xrrtss1511555269.jpg",
    strTags: "Pie,Meat",
    strYoutube: "https://www.youtube.com/watch?v=xr-CpPE_lNk",
    strIngredient1: "Chicken Stock",
    strIngredient2: "Chicken Breast",
    strIngredient3: "Butter",
    strIngredient4: "Leek",
    strIngredient5: "Garlic",
    strIngredient6: "Plain Flour",
    strIngredient7: "Milk",
    strIngredient8: "White Wine",
    strIngredient9: "Double Cream",
    strIngredient10: "Ham",
    strIngredient11: "Sea Salt",
    strIngredient12: "Pepper",
    strIngredient13: "Plain Flour",
    strIngredient14: "Butter",
    strIngredient15: "Free-range Egg, Beaten",
    strIngredient16: "Cold Water",
    strIngredient17: "Free-range Egg, Beaten",
    strIngredient18: "",
    strIngredient19: "",
    strIngredient20: "",
    strMeasure1: "450ml",
    strMeasure2: "3",
    strMeasure3: "75g",
    strMeasure4: "2 sliced",
    strMeasure5: "2 cloves minced",
    strMeasure6: "50g",
    strMeasure7: "200ml",
    strMeasure8: "3 tbs",
    strMeasure9: "150ml",
    strMeasure10: "150g",
    strMeasure11: "spinkling",
    strMeasure12: "pinch",
    strMeasure13: "350g",
    strMeasure14: "200g",
    strMeasure15: "1",
    strMeasure16: "1 tbls",
    strMeasure17: "1",
    strMeasure18: "",
    strMeasure19: "",
    strMeasure20: "",
    strSource:
      "https://www.bbc.co.uk/food/recipes/creamy_chicken_ham_and_03877",
    strImageSource: null,
    strCreativeCommonsConfirmed: null,
    dateModified: null,
  },
];

function details({ params: { id } }) {
  const [query, setQuery] = useState("");
  // console.log(query);
  const searchedValue = query.toLowerCase();
  function handleSearch(e) {
    e.preventDefault();
  }
  const searchedRecipe = recipies.filter((recipe) =>
    recipe.strMeal.includes(searchedValue)
  );
  const searchedByCategory = recipies.filter((recipe) =>
    recipe.strCategory.includes(searchedValue)
  );

  const allSearchedRecipes = [...searchedRecipe, ...searchedByCategory];
  // console.log(allSearchedRecipes, query);
  //   console.log(id);
  const filteredRecipe = recipies.find((recipe) => {
    return recipe.idMeal == Number(id);
  });
  //   console.log(filteredRecipe);
  return (
    <div
      className="flex flex-col  max-w-[85%] min-h-screen m-auto rounded-xl
     bg-violet-100 "
    >
      {/* HEADER */}
      <div className="flex rounded m-auto bg-violet-100 py-5    px-10 items-center justify-between gap-16 ">
        <div className="flex items-center">
          <div className="w-14 rounded-3xl ">
            <Image
              src=""
              alt="png"
              className="rounded-full "
              width={50}
              height={50}
            />
          </div>
          <h2 className="text-2xl font-serif font-bold">Forky</h2>
        </div>
        <form
          className="flex bg-slate-50 rounded-l-3xl  rounded-r-3xl gap-3"
          onSubmit={handleSearch}
        >
          <input
            type="text"
            value={query}
            onChange={(e) => setQuery(e.target.value)}
            placeholder="search over 10000 recipies"
            className="bg-slate-50 rounded-l-3xl outline-none px-6 py-2 "
          />

          <button
            type="submit"
            className="flex items-center justify-center rounded-t-3xl rounded-b-3xl gap-2 w-[150px] bg-violet-400 px-2 py-2"
          >
            {" "}
            <Search className="" />
            search
          </button>
        </form>
        <div className="flex gap-8">
          <li className="flex gap-2 decoration-none font-semibold">
            <Edit className="text-violet-800 font-extrabold" />
            <button className="">ADD RECIPE</button>
          </li>
          <li className="flex gap-2 decoration-none font-semibold">
            <Bookmark className="text-violet-800 font-extrabold" />
            <button>BOOKMARKS</button>
          </li>
        </div>
      </div>
      {/* <Header /> */}
      <div className="flex gap-4  w-[100%] min-h-screen">
        <div className="flex py-6 px-12 justify-start w-auto min-h-screen bg-violet-50">
          <div className="flex  flex-col gap-4">
            <div className="flex  flex-col gap-4">
              {allSearchedRecipes ? (
                allSearchedRecipes.map((recipe, i) => (
                  <Recipie recipe={recipe} key={i} />
                  // console.log(recipe)
                ))
              ) : (
                <div className="flex items-center">
                  <h2>NO SEARCHES FOUND</h2>
                </div>
              )}
            </div>
          </div>
        </div>
        <div className="flex  justify-center w-full h-[100vh] bg-violet-100">
          <RecipieDetails recipe={filteredRecipe} />
        </div>
      </div>
    </div>
  );
}

export default details;
